name: C Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        name: Build the code
        run: make

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./hello  # Specify the path to the built executable
